### PR TITLE
Schema/russian

### PR DESCRIPTION
**Pull request by gregsdennis**

### CODE REVIEW

**Comment by gregsdennis** [comment]
@askalione the Russian package will publish when I merge this PR.  The English fix I'll hold until I push out a new version.  Thanks for the contribution!

**Comment by gregsdennis** [comment]
In my [tests](https://github.com/gregsdennis/json-everything/blob/master/JsonSchema.Tests%2FLocalizationTests.cs#L32) I'm using the static `ErrorMessages.Culture` property.

I'm not sure why it's not working through the options though.  I'll have a look tomorrow.

**Comment by askalione** [comment]
I also trying with static `ErrorMessages.Culture`  property and it doesn't work too ...

In `ErrorMessages` class i see this line using `typeof(ErrorMessages).Assembly` for loading resources. 

```cs
private static readonly ResourceManager _resourceManager = new("Json.Schema.Localization.Resources", typeof(ErrorMessages).Assembly);
```

But translation now in separate assembly (in separate nuget package). That's why it doesn't work i think.
Or I'm wrong?

**Comment by gregsdennis** [comment]
I'm unable to replicate it not working.  Here's a solution:

[ConsoleApp2.zip](https://github.com/gregsdennis/json-everything/files/14302159/ConsoleApp2.zip)

**Comment by askalione** [comment]
Ohh, sorry, it was my mistake ... 😨

I have following settings in my root project (`.csproj`):

```xml
<PropertyGroup>
  <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
</PropertyGroup>
```

That's why `JsonSchema.Net.resources.dll` didn't copy under `/ru` directory when build.
When I changed settings in `.csproj` like:

```xml
<PropertyGroup>
  <SatelliteResourceLanguages>en;ru</SatelliteResourceLanguages>
</PropertyGroup>
```

All works fine! 🦾

Thank you very much 🙏! Sorry for spending your time 😓

**Comment by gregsdennis** [comment]
No worries. It should also work if you just remove that property.

**Pull request merged**
