### PR TITLE
Fix current uri

### PR DESCRIPTION
**Pull request by amosonn**
This is my attempt to correct the underlying issue in #79 (as mentioned there): sometimes `CurrentUri` was pointing to the parent of the actual current uri.

This is based on my updated test for #79, as in #81, so that one can be merged first or closed and then this one merged directly; and reverts your revert from #80, so that we are using `CurrentUri` in that case, and the test verifies that it is correct.

I'm pretty sure this should also fix diagonstics (verbose results) in some cases, I'll try to provide one later.

### CODE REVIEW

**Comment by amosonn** [comment]
Well, obviously in my test case it fixes validation, before this PR you get:

```json
{
   "valid": true,
   "keywordLocation": "#",
   "instanceLocation": "#",
   "annotations": [
     {
       "valid": true,
       "keywordLocation": "#/$ref",
       "absoluteKeywordLocation": "http://first.com/schema2.json#",
       "instanceLocation": "#",
       "annotations": [
         {
           "valid": true,
           "keywordLocation": "#/$ref",
           "absoluteKeywordLocation": "http://first.com/#",
           "instanceLocation": "#",
           "annotations": [
             {
               "valid": true,
               "keywordLocation": "#/$ref/$ref",
               "absoluteKeywordLocation": "http://first.com/#",
               "instanceLocation": "#",
               "annotations": [
                 {
                   "valid": true,
                   "keywordLocation": "#/$ref/$ref",
                   "absoluteKeywordLocation": "http://first.com/#/definitions/myDef",
                   "instanceLocation": "#",
                   "annotations": [
                     {
                       "valid": true,
                       "keywordLocation": "#/$ref/$ref/properties",
                       "absoluteKeywordLocation": "http://first.com/#/definitions/myDef/properties",
                       "instanceLocation": "#",
                       "annotation": [
                         "abc"
                       ]
                     }
                   ]
                 }
               ]
             }
           ]
         }
       ]
     }
   ]
 }
```

and after it you get:

```json
 {
   "valid": true,
   "keywordLocation": "#",
   "instanceLocation": "#",
   "annotations": [
     {
       "valid": true,
       "keywordLocation": "#/$ref",
       "absoluteKeywordLocation": "http://first.com/schema2.json#",
       "instanceLocation": "#",
       "annotations": [
         {
           "valid": true,
           "keywordLocation": "#/$ref",
           "absoluteKeywordLocation": "http://first.com/schema1.json#",
           "instanceLocation": "#",
           "annotations": [
             {
               "valid": true,
               "keywordLocation": "#/$ref/$ref",
               "absoluteKeywordLocation": "http://first.com/schema1.json#",
               "instanceLocation": "#",
               "annotations": [
                 {
                   "valid": true,
                   "keywordLocation": "#/$ref/$ref",
                   "absoluteKeywordLocation": "http://first.com/schema1.json#/definitions/myDef",
                   "instanceLocation": "#",
                   "annotations": [
                     {
                       "valid": true,
                       "keywordLocation": "#/$ref/$ref/properties",
                       "absoluteKeywordLocation": "http://first.com/schema1.json#/definitions/myDef/properties",
                       "instanceLocation": "#",
                       "annotation": [
                         "abc"
                       ]
                     }
                   ]
                 }
               ]
             }
           ]
         }
       ]
     }
   ]
 }
```

I'll try to add it to the test-case.

**Comment by amosonn** [comment]
I added a test-case to Json Schema Test Suite:
https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/457
It seems that this test-case fails under the current master, even after #80, and succeeds after this PR. Should I also add this test directly to the repo, as another variant of Issue79? Or should we wait for it to land in the Json Schema Test Suite?

**Comment by amosonn** [comment]
For consistency, I made the same changes to `DynamicRefKeyword` and `RecursiveRefKeyword`, but I didn't manage to build a good test case for them.

**Comment by gregsdennis** [comment]
This looks good, thanks.  I'll make some code style edits after merging this into the version branch, but functionally it's great!

**Comment by gregsdennis** [comment]
The build failures are from the action not liking PRs from forks.  Haven't cared enough to fix it yet.

**Pull request merged**
