### PR TITLE
date-time validation check using regex

### PR DESCRIPTION
**Pull request by faldor20**
DateTimes that have very high precision eg: 2023-03-20T05:41:23.802351665Z can be parsed by dotnet and are allowed by jsonschema but don't get accepted by TryParseExact
This uses regex as a fallback to check a datetime just incase it's actually compliant event though TryParseExact disagrees.

### CODE REVIEW

**Review by gregsdennis — CHANGES_REQUESTED** [review]
It looks like (line 19) that I only supply formats up to 7-digit precision.  Have you tried adding the additional digits here instead of regex?

Also can you add a unit test to cover this case, please?

**Comment by faldor20** [comment]
I did try that, unfortunately adding more does nothing. 
https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
It seems the list here is comprehensive. 
I couldn't see where you were testing it in the first place so I wasn't quite sure where to add a test.
If you point me in the right direction I'll happily do so though :)

Thanks for getting back to me so quick!

**Comment by gregsdennis** [comment]
> I couldn't see where you were testing it in the first place so I wasn't quite sure where to add a test.

Please add to `FormatTests`.

**Comment by gregsdennis** [comment]
Thanks.  I'm going to merge this into #418 just to combine releases.

**Review by gregsdennis — APPROVED** [review]

**Pull request merged**
