### PR TITLE
Issue 114 datetime schemagen

### LINKED ISSUE #114: DateTime Property generation not work correctly
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.10.2
- OS: Wndows 10
- .Net Target: .NET Core 3.1, .NET 5.0

**Describe the bug**
In my class I have DateTime property , when i pass it's value as string the method JsonSchema.Validate() returns  "Value is string but should be object"

**To Reproduce**

    public class BaseData

    {

        [Required]

        [JsonPropertyName("eventTime")]

        public DateTime EventTime { get; set; }

    }

    public static async Task<HttpResponseBody<T>> GetBodyAsync<T>(this HttpRequest request)
        {
          
            var bodyString = "{\r\n    \"eventTime\": \"2021-05-19T12:41:32-05:00\"\r\n}"
            JsonSchema schema = new JsonSchemaBuilder().FromType<BaseData>().Build(); //{\"type\":\"object\",\"properties\":{\"eventTime\":{\"type\":\"object\",\"properties\":{}}},\"required\":[\"eventTime\"]}
            ValidationOptions options = new ValidationOptions();
            options.OutputFormat = OutputFormat.Detailed;

            var validation = schema.Validate(JsonDocument.Parse(bodyString).RootElement, options);
     }

**Expected behavior**
When i run the proram, validation.Message return "Value is string but should be object" and Validation.IsValid returns false, but i expect it's work with Validation.IsValid = true

### PR DESCRIPTION
**Pull request by gregsdennis**
Fixes #114

### CODE REVIEW

**Comment by bahaasamoudi** [comment]
Hello @gregsdennis , but what if i pass string value to DateTime it will accepted and validation wil be true
Example:     {"eventTime": "2021-05-19T12:41:32-05:00StringStringStringTest"}

**Comment by gregsdennis** [comment]
`DateTime`s are validated [here](https://www.github.com/gregsdennis/json-everything/tree/master/JsonSchema%2FFormats.csL270) by default.  You can [override the format validation](https://gregsdennis.github.io/json-everything/usage/schema-validation.html#value-format-validation) of you want to.

**Comment by bahaasamoudi** [comment]
Hi @gregsdennis,
I mean in #114, I have EventTime  and it is Datetime Proeprty
In json proeprty when I pass EventTime  as string like "MyTestString" The validation.IsValid property returns true, but it must return false because MyTestString not DateTime ; it's string

**object**
`"{\r\n    \"eventTime\": \"MyTestString\",\r\n}"
`
**schema**

`"{\"type\":\"object\",\"properties\":{\"eventTime\":{\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"eventTime\"]}"
`


**Validation object**
image

**Class**

```
 public class BaseData
    {
        [Required]
        [JsonPropertyName("eventTime")]
        public DateTime EventTime { get; set; }
    }
```

**Comment by gregsdennis** [comment]
Per the specification, formats are not validated by default; they're annotations.  You can see it if you check the `Annotations` collection.

There's a lot of discussion on the JSON Schema spec repo, if you want to read through it.

Validation for formats can be engaged with the [`RequireFormatValidation` option](https://www.github.com/gregsdennis/json-everything/tree/master/JsonSchema%2FValidationOptions.csL89).

**Pull request merged**
