### PR TITLE
sweden and norway resources

### LINKED ISSUE #457: Localization for Sweden
**How can I help you today?**
Hi, we need validation errors localized for sweden, the same way it is done for es culture. If I were to provide translation would you be able to add support for it?

 I saw similar issue over here:
https://github.com/gregsdennis/json-everything/issues/298

### PR DESCRIPTION
**Pull request by pawel-wachalski**
Resolves #457 Adding resources for Sweden and Norway

### CODE REVIEW

**Comment by gregsdennis** [comment]
Thanks for these.  I'll get them in and published.

(I want to publish them as separate packages, but it seems that the Spanish resources are being added to the main package anyway.  I'll try to figure that out as well.)

**Comment by gregsdennis** [comment]
@pawel-wachalski I've merged this for now.  I'll need to set up a build to publish it.

**Comment by gregsdennis** [comment]
JsonSchema.Net v4.1.3 should now be available and should include these new languages.  Thank you again for this!

**Comment by pawel-wachalski** [comment]
Hi @gregsdennis is there a chance we can get them as a separate library like es resources were published? Currently, we are using version 2.3.0. of the library and we would like to avoid update at the moment?

**Comment by pawel-wachalski** [comment]
I understand the problem of repeated resources - in the main package and in the separate resource package. However if turns out troublesome, it would be helpful for me, if you publish the resources separately anyway - then it would be possible for me to achieve what I need - to have the resources while not upgrading to the newest version. How do you feel about it?

**Comment by gregsdennis** [comment]
Okay... so a lot of what I tried didn't work, but it does now.

Lessons learned:

- The resources MUST be built as part of the core project.  I can't build the localizations in a separate project.
- I can't use `dotnet pack` to build because the content isn't customizable, which means the localized resources will be included.
- That means I have to have _.nuspec_ files for everything and `nuget pack` them manually.

Thanks to the Humanizer project for already tackling this and publishing their work.

**Comment by gregsdennis** [comment]
The package is 1.0.1, but the lib's attributes say 4.0.0.  I've tested the packages that are uploaded to Nuget.  It all works.
[TestProject1.zip](https://github.com/gregsdennis/json-everything/files/11739059/TestProject1.zip)

The 1.0.0 versions of the lanugage packs should be unlisted.  You'll still be able to get to them, but don't use them.  I was figuring things out.  Use the 1.0.1 packages.

**Comment by pawel-wachalski** [comment]
@gregsdennis in you test project you are using JsonSchema.Net 4.1.5 version (newest) and this indeed works.
In my solution I use JsonSchema.Net 2.3.0 version and when I try to use resources I get following error:
image
So the questions if if we can make the reources packages work with JsonSchema.Net 2.3.0 too?

**Comment by gregsdennis** [comment]
No, it won't work with older versions. I'd have to recompile at that version.  I don't have a way to release older versions, and I'm pretty sure the messages wouldn't be compatible anyway.

**Comment by gregsdennis** [comment]
I think the primary problem is that the resources DLL's `[AssemblyVersion]` attribute needs to match the main DLL's `[AssemblyVersion]` in order for .Net to load it.

I wrote a blog post (a long time ago) that touches on this: https://gregsdennis.github.io/coding-for-smarties/2016/01/21/how-to-version-assemblies-destined-for-nuget.html

**Comment by pawel-wachalski** [comment]
@gregsdennis thanks for the explanations. I think there is one thing we might try, if you are willing to. In your nuspec for the resource you have defined a strict version for dependency like:
`   <dependencies>
      <dependency id="JsonSchema.Net" version="4.0.0" />
    </dependencies>`
Maybe defining it like:
``   <dependencies>
      <dependency id="JsonSchema.Net" version="2.3.0" />
    </dependencies>``
I think it might give the flexibility with the resources, not requiring to release any older versions of the main library. 

 _I'm pretty sure the messages wouldn't be compatible anyway._
 I am not sure, but there is a chance, that the resources provided, where made based on our local version of 2.3.0, not the newest - I assumed (not sure if correctly), that keys for the messages do not change overtime, maybe just a message itself.

**Comment by gregsdennis** [comment]
Sorry, but the assembly versiond have to match in order for the .net runtime to load the resource assembly and associate it with the cute assembly.  Just updating the dependency in the Nuget package won't help.

**Pull request merged**
